-- MySQL Script generated by MySQL Workbench
-- jeu 05 oct 2017 14:49:35 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pclist` ;

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pclist` DEFAULT CHARACTER SET utf8 ;
USE `pclist` ;

-- -----------------------------------------------------
-- Table `pclist`.`cpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`cpu` (
  `idCpu` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  `nbCores` INT UNSIGNED NULL,
  `frequency` DOUBLE UNSIGNED NULL,
  PRIMARY KEY (`idCpu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pclist`.`gpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`gpu` (
  `idGpu` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  PRIMARY KEY (`idGpu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pclist`.`ram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`ram` (
  `idRam` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  `size` INT UNSIGNED NULL,
  PRIMARY KEY (`idRam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pclist`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`pc` (
  `idPc` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NULL,
  `price` INT UNSIGNED NULL,
  `idCpu` INT NOT NULL,
  `idGpu` INT NOT NULL,
  `idRam` INT NOT NULL,
  PRIMARY KEY (`idPc`),
  INDEX `fk_Pc_Cpu_idx` (`idCpu` ASC),
  INDEX `fk_Pc_Gpu1_idx` (`idGpu` ASC),
  INDEX `fk_Pc_Ram1_idx` (`idRam` ASC),
  CONSTRAINT `fk_Pc_Cpu`
    FOREIGN KEY (`idCpu`)
    REFERENCES `pclist`.`cpu` (`idCpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Gpu1`
    FOREIGN KEY (`idGpu`)
    REFERENCES `pclist`.`gpu` (`idGpu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Ram1`
    FOREIGN KEY (`idRam`)
    REFERENCES `pclist`.`ram` (`idRam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pclist`.`cpu`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `nbCores`, `frequency`) VALUES (DEFAULT, 'intel', 3, 2.3);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `nbCores`, `frequency`) VALUES (DEFAULT, 'amd', 4, 4);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pclist`.`gpu`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`gpu` (`idGpu`, `brand`) VALUES (DEFAULT, 'nvidea');
INSERT INTO `pclist`.`gpu` (`idGpu`, `brand`) VALUES (DEFAULT, 'amd');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pclist`.`ram`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`ram` (`idRam`, `brand`, `size`) VALUES (DEFAULT, 'corsaire', 4);
INSERT INTO `pclist`.`ram` (`idRam`, `brand`, `size`) VALUES (DEFAULT, 'fury', 8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pclist`.`pc`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`pc` (`idPc`, `brand`, `price`, `idCpu`, `idGpu`, `idRam`) VALUES (DEFAULT, 'Dell', 3000, 1, 1, 1);
INSERT INTO `pclist`.`pc` (`idPc`, `brand`, `price`, `idCpu`, `idGpu`, `idRam`) VALUES (DEFAULT, 'Asus', 1000, 2, 2, 2);

COMMIT;

