-- MySQL Script generated by MySQL Workbench
-- jeu 05 oct 2017 14:49:35 CEST
-- Model: PcList    Version: 1.0
-- MySQL Workbench Forward Engineering
-- author: Loan Lassalle
-- author: Jérémie Zanone

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pclist`;

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pclist`
  DEFAULT CHARACTER SET utf8;
USE `pclist`;

-- -----------------------------------------------------
-- Table `pclist`.`cpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`cpu` (
  `idCpu`     INT             NOT NULL AUTO_INCREMENT,
  `brand`     VARCHAR(45)     NOT NULL,
  `cores`     INT UNSIGNED    NOT NULL,
  `frequency` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`idCpu`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`ram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`ram` (
  `idRam` INT          NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45)  NOT NULL,
  `size`  INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRam`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`gpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`gpu` (
  `idGpu` INT         NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGpu`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`pc` (
  `idPc`  INT             NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45)     NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `idCpu` INT             NOT NULL,
  `idGpu` INT             NOT NULL,
  `idRam` INT             NOT NULL,
  PRIMARY KEY (`idPc`),
  INDEX `fk_Pc_Cpu_idx` (`idCpu` ASC),
  INDEX `fk_Pc_Gpu1_idx` (`idGpu` ASC),
  INDEX `fk_Pc_Ram1_idx` (`idRam` ASC),
  CONSTRAINT `fk_Pc_Cpu`
  FOREIGN KEY (`idCpu`)
  REFERENCES `pclist`.`cpu` (`idCpu`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Gpu1`
  FOREIGN KEY (`idGpu`)
  REFERENCES `pclist`.`gpu` (`idGpu`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Ram1`
  FOREIGN KEY (`idRam`)
  REFERENCES `pclist`.`ram` (`idRam`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pclist`.`cpu`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'Intel', 1, 1.1);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'AMD', 1, 1.2);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'Intel', 2, 2.1);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'AMD', 2, 2.2);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'Intel', 3, 3.1);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'AMD', 3, 3.2);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'Intel', 4, 4.1);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'AMD', 4, 4.2);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'Intel', 5, 5.1);
INSERT INTO `pclist`.`cpu` (`idCpu`, `brand`, `cores`, `frequency`) VALUES (DEFAULT, 'AMD', 5, 5.2);

COMMIT;

-- -----------------------------------------------------
-- Data for table `pclist`.`ram`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`ram` (`idRam`, `brand`, `size`) VALUES (DEFAULT, 'Corsaire', 4);
INSERT INTO `pclist`.`ram` (`idRam`, `brand`, `size`) VALUES (DEFAULT, 'Fury', 8);

COMMIT;

-- -----------------------------------------------------
-- Data for table `pclist`.`gpu`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`gpu` (`idGpu`, `brand`) VALUES (DEFAULT, 'NVIDIA');
INSERT INTO `pclist`.`gpu` (`idGpu`, `brand`) VALUES (DEFAULT, 'AMD');

COMMIT;

-- -----------------------------------------------------
-- Data for table `pclist`.`pc`
-- -----------------------------------------------------
START TRANSACTION;
USE `pclist`;
INSERT INTO `pclist`.`pc` (`idPc`, `brand`, `price`, `idCpu`, `idGpu`, `idRam`)
VALUES (DEFAULT, 'Dell', 3000.99, 1, 1, 1);
INSERT INTO `pclist`.`pc` (`idPc`, `brand`, `price`, `idCpu`, `idGpu`, `idRam`)
VALUES (DEFAULT, 'Asus', 1000.99, 2, 2, 2);

COMMIT;

