-- MySQL Script generated by MySQL Workbench
-- jeu 05 oct 2017 14:49:35 CEST
-- Model: PcList    Version: 1.0
-- MySQL Workbench Forward Engineering
-- author: Loan Lassalle
-- author: Jérémie Zanone

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pclist`;

-- -----------------------------------------------------
-- Schema pclist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pclist`
  DEFAULT CHARACTER SET utf8;
USE `pclist`;

-- -----------------------------------------------------
-- Table `pclist`.`cpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`cpu` (
  `idCpu`     INT             NOT NULL AUTO_INCREMENT,
  `brand`     VARCHAR(45)     NOT NULL,
  `cores`     INT UNSIGNED    NOT NULL,
  `frequency` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`idCpu`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`ram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`ram` (
  `idRam` INT          NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45)  NOT NULL,
  `size`  INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRam`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`gpu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`gpu` (
  `idGpu` INT         NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGpu`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `pclist`.`pc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pclist`.`pc` (
  `idPc`  INT             NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45)     NOT NULL,
  `price` DOUBLE UNSIGNED NOT NULL,
  `idCpu` INT             NOT NULL,
  `idGpu` INT             NOT NULL,
  `idRam` INT             NOT NULL,
  PRIMARY KEY (`idPc`),
  INDEX `fk_Pc_Cpu_idx` (`idCpu` ASC),
  INDEX `fk_Pc_Gpu1_idx` (`idGpu` ASC),
  INDEX `fk_Pc_Ram1_idx` (`idRam` ASC),
  CONSTRAINT `fk_Pc_Cpu`
  FOREIGN KEY (`idCpu`)
  REFERENCES `pclist`.`cpu` (`idCpu`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Gpu1`
  FOREIGN KEY (`idGpu`)
  REFERENCES `pclist`.`gpu` (`idGpu`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pc_Ram1`
  FOREIGN KEY (`idRam`)
  REFERENCES `pclist`.`ram` (`idRam`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;